#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn husky add .husky/commit-msg 'yarn commitlint --edit $1'
yarn commitlint --edit $1
yarn commitlint --edit $1
yarn commitlint --edit $1
yarn commitlint --edit $1
